### ISSUE TITLE
Auto-fix should not be enabled by default

### ISSUE THREAD

**Issue by dhhyi** [kaiza/tslint-jasmine-rules#14]
Hi,

when we are using the tslint-jasmine-rules with an IDE like VSCode, that has auto-fixing for tslint issues enabled on save, we can no longer focus tests by adding an 'f' and save as the auto-fixing takes place before the following test run. The fixing should not be mandatory but optional as intended by #11.

**Comment by kaiza** [comment]
@dhhyi VS Code supports opting in the rules to auto fix on save. See this discussion https://github.com/Microsoft/vscode-tslint/issues/362

As you can see in that discussion there are other rules that are also potentially problematic with auto fix.

**Comment by dhhyi** [comment]
Okay, that's one way of solving this :sweat_smile: 

We're fine with the original just-warning behavior in 1.4.0, so we'll stick to that for now...

**Comment by kaiza** [comment]
@dhhyi In case you're interested it's now possible to disable auto-fixing by setting the rule severity to warning, as of version 1.6.0.
